<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-4FMUS56" name="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP" tests="13" failures="2" timestamp="2020-04-13T22:22:37 IST" time="63.965" errors="0">
  <testcase name="forgotpassword0" time="16.710" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword1" time="0.406" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword2" time="2.663" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword3" time="5.302" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP.forgotpassword3(TC_ForgotPassword_002_OTP.java:118)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- forgotpassword3 -->
  <system-out/>
  <testcase name="forgotpassword4" time="5.462" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword5" time="0.133" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword6" time="4.953" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword7" time="2.625" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword8" time="4.915" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword9" time="4.949" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword10" time="4.884" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword11" time="5.277" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP"/>
  <system-out/>
  <testcase name="forgotpassword12" time="5.686" classname="com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP.forgotpassword12(TC_ForgotPassword_002_OTP.java:352)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- forgotpassword12 -->
  <system-out/>
</testsuite> <!-- com.MarshPanel.TestCases.TC_ForgotPassword_002_OTP -->
